<?php

namespace App\Application\Services;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-08-31 at 02:21:47.
 */
class HorseServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var HorseService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HorseService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
}
