<?php

namespace App\Application\Services;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-08-31 at 02:21:47.
 */
class RaceServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RaceService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RaceService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers App\Application\Services\RaceService::moveAllHorses
     * @todo   Implement testMoveAllHorses().
     */
    public function testMoveAllHorses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
