<?php

namespace App\Domain\Model\Race;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-08-31 at 02:22:00.
 */
class RaceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Race
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Race;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers App\Domain\Model\Race\Race::init
     * @todo   Implement testInit().
     */
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Race\Race::addRunningHorse
     * @todo   Implement testAddRunningHorse().
     */
    public function testAddRunningHorse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Race\Race::moveHorses
     * @todo   Implement testMoveHorses().
     */
    public function testMoveHorses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Race\Race::isOver
     * @todo   Implement testIsOver().
     */
    public function testIsOver()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Race\Race::isStillRunning
     * @todo   Implement testIsStillRunning().
     */
    public function testIsStillRunning()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Race\Race::horses
     * @todo   Implement testHorses().
     */
    public function testHorses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Race\Race::distance
     * @todo   Implement testDistance().
     */
    public function testDistance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
