<?php

namespace App\Domain\Model\Race;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-08-31 at 02:22:00.
 */
class RaceFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RaceFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RaceFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers App\Domain\Model\Race\RaceFactory::make
     * @todo   Implement testMake().
     */
    public function testMake()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
