<?php

namespace App\Domain\Model\Horse\Stats;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-08-31 at 02:21:25.
 */
class EnduranceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Endurance
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Endurance;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers App\Domain\Model\Horse\Stats\Endurance::value
     * @todo   Implement testValue().
     */
    public function testValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Horse\Stats\Endurance::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
