<?php

namespace App\Domain\Model\Horse\Stats;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-08-31 at 02:21:25.
 */
class HorseStatsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var HorseStats
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HorseStats;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers App\Domain\Model\Horse\Stats\HorseStats::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Horse\Stats\HorseStats::speed
     * @todo   Implement testSpeed().
     */
    public function testSpeed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Horse\Stats\HorseStats::strength
     * @todo   Implement testStrength().
     */
    public function testStrength()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Horse\Stats\HorseStats::endurance
     * @todo   Implement testEndurance().
     */
    public function testEndurance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Horse\Stats\HorseStats::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
