<?php

namespace App\Domain\Model\Horse\Stats;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-08-31 at 02:21:01.
 */
class SpeedTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Speed
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Speed;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers App\Domain\Model\Horse\Stats\Speed::init
     * @todo   Implement testInit().
     */
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Horse\Stats\Speed::subtract
     * @todo   Implement testSubtract().
     */
    public function testSubtract()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Horse\Stats\Speed::distance
     * @todo   Implement testDistance().
     */
    public function testDistance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Horse\Stats\Speed::time
     * @todo   Implement testTime().
     */
    public function testTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Horse\Stats\Speed::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
