<?php

namespace App\Domain\Model\Race\Stats;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-08-31 at 02:22:00.
 */
class RunningHorseStatsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RunningHorseStats
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RunningHorseStats;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers App\Domain\Model\Race\Stats\RunningHorseStats::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Race\Stats\RunningHorseStats::start
     * @todo   Implement testStart().
     */
    public function testStart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Race\Stats\RunningHorseStats::increase
     * @todo   Implement testIncrease().
     */
    public function testIncrease()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Race\Stats\RunningHorseStats::increaseTime
     * @todo   Implement testIncreaseTime().
     */
    public function testIncreaseTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Race\Stats\RunningHorseStats::updateTime
     * @todo   Implement testUpdateTime().
     */
    public function testUpdateTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Race\Stats\RunningHorseStats::increaseDistance
     * @todo   Implement testIncreaseDistance().
     */
    public function testIncreaseDistance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Race\Stats\RunningHorseStats::distance
     * @todo   Implement testDistance().
     */
    public function testDistance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Race\Stats\RunningHorseStats::time
     * @todo   Implement testTime().
     */
    public function testTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers App\Domain\Model\Race\Stats\RunningHorseStats::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
